alter table MARKET_PRODUCER add constraint FK_MARKET_PRODUCER_ON_ADDRESS foreign key (ADDRESS_ID) references MARKET_ADDRESS(ID);
create index IDX_MARKET_PRODUCER_ON_ADDRESS on MARKET_PRODUCER (ADDRESS_ID);
