alter table MARKET_PRODUCT add constraint FK_MARKET_PRODUCT_ON_PRODUCER foreign key (PRODUCER_ID) references MARKET_PRODUCER(ID);
create unique index IDX_MARKET_PRODUCT_UNIQ_NAME on MARKET_PRODUCT (NAME) ;
create index IDX_MARKET_PRODUCT_ON_PRODUCER on MARKET_PRODUCT (PRODUCER_ID);
