alter table MARKET_PRICE_HISTORY add constraint FK_MARKET_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references MARKET_PRODUCT(ID);
alter table MARKET_PRICE_HISTORY add constraint FK_MARKET_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references MARKET_SHOP(ID);
create index IDX_MARKET_PRICE_HISTORY_ON_PRODUCT on MARKET_PRICE_HISTORY (PRODUCT_ID);
create index IDX_MARKET_PRICE_HISTORY_ON_SHOP on MARKET_PRICE_HISTORY (SHOP_ID);
