alter table MARKET_PRODUCER add constraint FK_MARKET_PRODUCER_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MARKET_COMMERCIAL_NETWORK(ID);
create unique index IDX_MARKET_PRODUCER_UNIQ_NAME on MARKET_PRODUCER (NAME) ;
create index IDX_MARKET_PRODUCER_ON_COMMERCIAL_NETWORK on MARKET_PRODUCER (COMMERCIAL_NETWORK_ID);
