alter table MARKET_SHOP add constraint FK_MARKET_SHOP_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MARKET_COMMERCIAL_NETWORK(ID);
create unique index IDX_MARKET_SHOP_UNIQ_NO_ on MARKET_SHOP (NO_) ;
create index IDX_MARKET_SHOP_ON_COMMERCIAL_NETWORK on MARKET_SHOP (COMMERCIAL_NETWORK_ID);
