-- begin MARKET_PRODUCT
alter table MARKET_PRODUCT add constraint FK_MARKET_PRODUCT_ON_PRODUCER foreign key (PRODUCER_ID) references MARKET_PRODUCER(ID)^
create unique index IDX_MARKET_PRODUCT_UK_NAME on MARKET_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_MARKET_PRODUCT_ON_PRODUCER on MARKET_PRODUCT (PRODUCER_ID)^
-- end MARKET_PRODUCT
-- begin MARKET_SHOP
alter table MARKET_SHOP add constraint FK_MARKET_SHOP_ON_ADDRESS foreign key (ADDRESS_ID) references MARKET_ADDRESS(ID)^
alter table MARKET_SHOP add constraint FK_MARKET_SHOP_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MARKET_COMMERCIAL_NETWORK(ID)^
create unique index IDX_MARKET_SHOP_UK_NO_ on MARKET_SHOP (NO_) where DELETE_TS is null ^
create index IDX_MARKET_SHOP_ON_ADDRESS on MARKET_SHOP (ADDRESS_ID)^
create index IDX_MARKET_SHOP_ON_COMMERCIAL_NETWORK on MARKET_SHOP (COMMERCIAL_NETWORK_ID)^
-- end MARKET_SHOP
-- begin MARKET_PURCHASE
alter table MARKET_PURCHASE add constraint FK_MARKET_PURCHASE_ON_GOODS foreign key (GOODS_ID) references MARKET_GOODS(ID)^
alter table MARKET_PURCHASE add constraint FK_MARKET_PURCHASE_ON_SHIPMENT foreign key (SHIPMENT_ID) references MARKET_SHIPMENT(ID)^
create index IDX_MARKET_PURCHASE_ON_GOODS on MARKET_PURCHASE (GOODS_ID)^
create index IDX_MARKET_PURCHASE_ON_SHIPMENT on MARKET_PURCHASE (SHIPMENT_ID)^
-- end MARKET_PURCHASE
-- begin MARKET_PRODUCER
alter table MARKET_PRODUCER add constraint FK_MARKET_PRODUCER_ON_ADDRESS foreign key (ADDRESS_ID) references MARKET_ADDRESS(ID)^
alter table MARKET_PRODUCER add constraint FK_MARKET_PRODUCER_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MARKET_COMMERCIAL_NETWORK(ID)^
create unique index IDX_MARKET_PRODUCER_UK_NAME on MARKET_PRODUCER (NAME) where DELETE_TS is null ^
create index IDX_MARKET_PRODUCER_ON_ADDRESS on MARKET_PRODUCER (ADDRESS_ID)^
create index IDX_MARKET_PRODUCER_ON_COMMERCIAL_NETWORK on MARKET_PRODUCER (COMMERCIAL_NETWORK_ID)^
-- end MARKET_PRODUCER
-- begin MARKET_COMMERCIAL_NETWORK
create unique index IDX_MARKET_COMMERCIAL_NETWORK_UK_NAME on MARKET_COMMERCIAL_NETWORK (NAME) where DELETE_TS is null ^
-- end MARKET_COMMERCIAL_NETWORK
-- begin MARKET_PRICE_HISTORY
alter table MARKET_PRICE_HISTORY add constraint FK_MARKET_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references MARKET_SHOP(ID)^
alter table MARKET_PRICE_HISTORY add constraint FK_MARKET_PRICE_HISTORY_ON_GOODS foreign key (GOODS_ID) references MARKET_GOODS(ID)^
create index IDX_MARKET_PRICE_HISTORY_ON_SHOP on MARKET_PRICE_HISTORY (SHOP_ID)^
create index IDX_MARKET_PRICE_HISTORY_ON_GOODS on MARKET_PRICE_HISTORY (GOODS_ID)^
-- end MARKET_PRICE_HISTORY
-- begin MARKET_SHIPMENT
alter table MARKET_SHIPMENT add constraint FK_MARKET_SHIPMENT_ON_SHOP foreign key (SHOP_ID) references MARKET_SHOP(ID)^
create index IDX_MARKET_SHIPMENT_ON_SHOP on MARKET_SHIPMENT (SHOP_ID)^
-- end MARKET_SHIPMENT
-- begin MARKET_GOODS
alter table MARKET_GOODS add constraint FK_MARKET_GOODS_ON_PRODUCT foreign key (PRODUCT_ID) references MARKET_PRODUCT(ID)^
alter table MARKET_GOODS add constraint FK_MARKET_GOODS_ON_SHOP foreign key (SHOP_ID) references MARKET_SHOP(ID)^
create index IDX_MARKET_GOODS_ON_PRODUCT on MARKET_GOODS (PRODUCT_ID)^
create index IDX_MARKET_GOODS_ON_SHOP on MARKET_GOODS (SHOP_ID)^
-- end MARKET_GOODS
